# .readthedocs.yml
version: 2

# Configuration for Sphinx documentation
sphinx:
  configuration: docs/source/conf.py

# Formats for documentation
formats:
  - htmlzip
  - pdf
  - epub

# Python configuration
python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .

# Additional configurations (optional)
build:
  os: "ubuntu-22.04"
  tools:
    python: "3.11"
    # image: latest  # Use the latest image for the build environment

# Submodules configuration (if your project has submodules)
submodules:
  include: all   # Include all submodules
  recursive: true

# Environment variables (if needed)
# env:
#   READTHEDOCS: True

# Consider adding any other specific configurations required by your project
