name: Build Documentation

on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r docs/requirements.txt

      - name: Build Documentation with Sphinx
        run: |
          cd docs
          make html
        env:
          READTHEDOCS: 'True'

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Documentation
          path: docs/_build/html/
